1.What is a python libary? Why do we use Python libaries?

In [73]:
'''Python libaries consist of various pre written code and functions helps in 
building our projects and helps programmer focus of buisness problem rather than 
write code from scratch for it.

This python libaries developed and maintained by python community there are various types 
of python libaries present for diffrent fields like for data analysis, web development and  mashine learning.
and Ai and much more. 

Why do we use Python libaries

1.Libaries contain pre written code that we can reuse in diffrent project without writting it from 
scratch 
2.It saves time and increase productivity.
3.This libaries are well optimized and maintained libaries provided 
quality ready to use code for development.
4.There is a well written documentation for every libaries so it is easy to read 
and implement code. '''




'Python libaries consist of various pre written code and functions helps in \nbuilding our projects and helps programmer focus of buisness problem rather than \nwrite code from scratch for it.\n\nThis python libaries developed and maintained by python community there are various types \nof python libaries present for diffrent fields like for data analysis, web development and  mashine learning.\nand Ai and much more. \n\nWhy do we use Python libaries\n\n1.Libaries contain pre written code that we can reuse in diffrent project without writting it from \nscratch \n2.It saves time and increase productivity.\n3.This libaries are well optimized and maintained libaries provided \nquality ready to use code for development.\n4.There is a well written documentation for every libaries so it is easy to read \nand implement code. '

2.What is the diffrence between Numpy array and List?

In [74]:
'''Numpy array 

1.Then are homogenious means store only one type of data.
2.Numpy arrays store data in contiguous memory blocks.
3.Numpy array are fast and perform better on numerical data.
4.Numpy array consist of more prebuild functions than list used to perform 
data manuplation.

Python List

1.List stores diffrent types of data like string and int.
2.Python list store references to object in memory.
3.List are little slow than array.
4.As compare to array list consist of less number of predefined functions.
'''

'Numpy array \n\n1.Then are homogenious means store only one type of data.\n2.Numpy arrays store data in contiguous memory blocks.\n3.Numpy array are fast and perform better on numerical data.\n4.Numpy array consist of more prebuild functions than list used to perform \ndata manuplation.\n\nPython List\n\n1.List stores diffrent types of data like string and int.\n2.Python list store references to object in memory.\n3.List are little slow than array.\n4.As compare to array list consist of less number of predefined functions.\n'

3.Find the shape, size and dimension of the following array?

[[1,2,3,4],
[5,6,7,8],
[9,10,11,12]]

In [75]:
import numpy as np 

matrix=[[1,2,3,4],[5,6,7,8],[9,10,11,12]]
print(np.array(matrix).shape)



(3, 4)


4.Write python code to access the first row of the following array?
[[1,2,3,4],
[5,6,7,8],
[9,10,11,12]]

In [76]:
arr = [[1,2,3,4],[5,6,7,8],[9,10,11,12]]
print(arr[0])

[1, 2, 3, 4]


5.How do you access the element at the third row and fourth column from the given numpy array?
[[1,2,3,4],
[5,6,7,8],
[9,10,11,12]]

In [77]:
arr =[[1,2,3,4],[5,6,7,8],[9,10,11,12]]

print((arr[2])[3])

12


6.Write code to extract all odd-indexed element from the given numpy array?
[[1,2,3,4],
[5,6,7,8],
[9,10,11,12]]

In [78]:
odd_nums = []

arr = [[1,2,3,4],
[5,6,7,8],
[9,10,11,12]]

a = np.array(arr)
a[:,1::2]


array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

7.How can you generate a random 3x3 matrix with values between 0 and 1?

In [79]:
import numpy as np 


matrix = np.random.rand(3,3)
matrix

array([[0.49732467, 0.57542257, 0.82472612],
       [0.64105532, 0.71194158, 0.34202482],
       [0.78401654, 0.96362978, 0.92938842]])

8.Describe the diffrence between np.random.rand and np.randn ?

In [80]:
'''1.Both produce random nubers but from diffrent distribution 
The np.random.rand() function generates random numbers from a 
uniform distribution over the range [0, 1)

2.we can get array of random numbers by giving dimensions as a argument.

3.The np.random.randn() function generates random numbers from a 
standard normal distribution of mean = 0 and  standard deviation = 1

''' 

'1.Both produce random nubers but from diffrent distribution \nThe np.random.rand() function generates random numbers from a \nuniform distribution over the range [0, 1)\n\n2.we can get array of random numbers by giving dimensions as a argument.\n\n3.The np.random.randn() function generates random numbers from a \nstandard normal distribution of mean = 0 and  standard deviation = 1\n\n'

9.Write code to increase the dimension of the following array?

[[1,2,3,4],
[5,6,7,8],
[9,10,11,12]]

In [81]:
arr = [[1,2,3,4],
[5,6,7,8],
[9,10,11,12]]

print('Before',np.ndim(arr))

arr2 = np.expand_dims(arr, axis=1)
print('After',arr2.ndim)



Before 2
After 3


10.Consider the following matrix

A:[[1,2,3,4],[5,6,7,8],[9,10,11,12]]
B:[[1,2,3,4],[5,6,7,8],[9,10,11,12]]

In [82]:
# 1.Index wise multiplication

A=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
B=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])


multip= A*B 
multip



array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

In [83]:
# 2.Matrix multiplication.

ans = np.dot(A,B.reshape(4,3))
ans 

array([[ 70,  80,  90],
       [158, 184, 210],
       [246, 288, 330]])

In [84]:
# 3. Add both the matrix 

ans  = A+B
ans

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [85]:
# 4.Subtract matrix B from A 

ans = A-B
ans 

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [86]:
# 5.Divide Matrix B by A. 

ans = B/A
ans 

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

12.which function in numpy can be used to swap the byte order of an array?

In [87]:
'''np.ndarray.byteswap() This function used to swap the byte 
order of an array in numpy'''

'np.ndarray.byteswap() This function used to swap the byte \norder of an array in numpy'

13.what is the signification of the np.linalg.inv function?

In [88]:
'''The np.linalg.inv function in numpy used to calculate inverse of a matrix
this function used in solving system of linear equations finding determinant and performing 
transformations.'''

'The np.linalg.inv function in numpy used to calculate inverse of a matrix\nthis function used in solving system of linear equations finding determinant and performing \ntransformations.'

14.What does the np.reshape function do, and how is it used?

In [89]:
'''np.reshape function change the shape of array into desired form without changing the data 
it rearrange elements of array into new shape we want
we have to specify the shape 


To use this we have to simply import numpy and then use as a 
np.reshape(array_name,(n,m))
m is number of columns 
n is number of rows'''

'np.reshape function change the shape of array into desired form without changing the data \nit rearrange elements of array into new shape we want\nwe have to specify the shape \n\n\nTo use this we have to simply import numpy and then use as a \nnp.reshape(array_name,(n,m))\nm is number of columns \nn is number of rows'

15.what is broadcasting in Numpy?

In [90]:
'''With broadcasting in numpy array means we can able to perform arthimatics 
operations on two array like addition subtraction multiplication and division 
The array may be of diffrent shapes but compatable to each other to perform 
broadcasting.'''


'With broadcasting in numpy array means we can able to perform arthimatics \noperations on two array like addition subtraction multiplication and division \nThe array may be of diffrent shapes but compatable to each other to perform \nbroadcasting.'